#!/usr/bin/env python

import argparse
import urllib2
import json

def arg_parser():
    parser = argparse.ArgumentParser()
    parser.add_argument('--host', required=True,
            help='Marathon host:port (e.g. "10.0.0.10:8080")')
    parser.add_argument('--app', required=True,
            help='Name of application (e.g. "myapp")')
    return parser

def main(argv=None):
    parser = arg_parser()
    args = parser.parse_args(argv)
    url = "http://{0}/v2/apps/{1}".format(args.host, args.app)
    appdata = json.loads(urllib2.urlopen(url).read())
    print "{0}:{1}".format(appdata['app']['tasks'][0]['host'],
            appdata['app']['tasks'][0]['ports'][0])


if __name__ == '__main__':
    main()
    exit(0)
